<a href="https://colab.research.google.com/github/kalyankargouri/ANN/blob/main/experiment8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#implement lms
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

X = np.array([[1],[2],[3],[4],[5]])
Y = np.array([[2],[4],[6],[8],[10]])

# Normalize features
X = (X - np.mean(X)) / np.std(X)

# Add bias term to X
X = np.hstack((np.ones((X.shape[0], 1)), X))  # Shape: (n_samples, 2)

w = np.random.randn(2, 1)  # Initialize weights randomly
lr = 0.01
epochs = 160

for epoch in range(epochs):
    for i in range(X.shape[0]):
        xi = X[i].reshape(1, -1)  # Shape: (1, 2)
        yi = Y[i].reshape(1, -1)  # Shape: (1, 1)

        y_pred = np.dot(xi, w)  # Shape: (1, 1)

        error = yi - y_pred  # Shape: (1, 1)

        # gradient = -2 * xi.T.dot(error)  # Shape: (2, 1)

        # w -= lr * gradient

        w = w + lr * xi.T * error

    if epoch % 10 == 0:
        y_all_pred = np.dot(X, w)
        mse = np.mean((Y - y_all_pred) ** 2)
        print(f"Epoch {epoch}, MSE: {mse}")

print("\nFinal Weights:\n", w)
print("\nPredictions:")
predictions = np.dot(X, w)
print(predictions.round(2))

Epoch 0, MSE: 38.00680687673067
Epoch 10, MSE: 13.831938161725688
Epoch 20, MSE: 5.033878366766195
Epoch 30, MSE: 1.8319786813181458
Epoch 40, MSE: 0.6667087079440241
Epoch 50, MSE: 0.24263298913835568
Epoch 60, MSE: 0.08830017690393865
Epoch 70, MSE: 0.03213448157356334
Epoch 80, MSE: 0.011694428855460435
Epoch 90, MSE: 0.004255834430446293
Epoch 100, MSE: 0.0015487753071482166
Epoch 110, MSE: 0.0005636247914763722
Epoch 120, MSE: 0.0002051113695042739
Epoch 130, MSE: 7.464270186651832e-05
Epoch 140, MSE: 2.7163325250920415e-05
Epoch 150, MSE: 9.884995532004297e-06

Final Weights:
 [[5.99818193]
 [2.82760586]]

Predictions:
[[ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]]


In [10]:
def gradient_descent(X, Y, lr=0.01, epochs=1000):
    weights = np.random.randn(X.shape[1], 1)
    gd_losses = []

    for epoch in range(epochs):
        y_pred = np.dot(X, weights)
        error = y_pred - Y
        dw = np.dot(X.T, error) / len(X)
        weights -= lr * dw

        loss = np.mean((Y - y_pred) ** 2)
        gd_losses.append(loss)

    return weights, gd_losses

w_gd, gd_loss = gradient_descent(X, Y)
pred_gd = X @ w_gd
print("GD Weights:\n", w_gd)
print("\nGD Predictions:")
print(pred_gd.round(2))

GD Weights:
 [[5.99976177]
 [2.82832732]]

GD Predictions:
[[ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]]
